title: Heart_distance_test
project_dir: '/homes/rlops/regression'
seed: 42

experiment:
  name: Regression

data_loader:
  dataset_name: Heart
  dataset: /homes/rlops/Task02_Heart
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  batch_size: 9
  num_workers: 48
  patch_shape:
  - 80
  - 80
  - 80
  resize_shape:
  - 100
  - 250
  - 250
  sampler_type: grid
  grid_overlap: 0
  labels: null

model:
  name: PosPadUNet3D

loss:
  name: MSELoss

evaluation:
  - MSE
  - MAE
  - R2

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  do_prediction: False
  predict: ''
  epochs: 100