title: log_image_ok
project_dir: '/home/rlops/dlms'
seed: 42

experiment:
  name: Segmentation

data_loader:
  dataset_name: Heart
  dataset: /homes/rlops/alveolar_canal/Task02_Heart
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 9
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 48
  patch_shape:
  - 80
  - 80
  - 80
  resize_shape:
  - 100
  - 220
  - 220
  sampler_type: grid
  grid_overlap: 0
  volumes_max: 2100
  volumes_min: 0

model:
  name: PosPadUNet3D

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  do_prediction: False
  predict: ''
  epochs: 10